
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDECOLON COMMA DIVIDE ID JUGADOR LPAREN MINUS NUMBER PLUS REMATE RPAREN TIMESprogram : function_listfunction_list : function_list function\n                     | functionfunction : JUGADOR ID LPAREN param_list RPAREN COLON statementparam_list : param_list COMMA ID\n                  | ID\n                  | emptystatement : REMATE expression\n    expression : expression PLUS expression\n               | expression MINUS expression\n               | expression TIMES expression\n               | expression DIVIDE expression\n               | primary\n    primary : NUMBERprimary : IDprimary : ID LPAREN arg_list RPARENprimary : LPAREN expression RPARENarg_list : arg_list COMMA expression\n                | expression\n                | emptyempty :'
    
_lr_action_items = {'JUGADOR':([0,2,3,5,15,17,18,19,20,28,29,30,31,35,36,],[4,4,-3,-2,-4,-8,-13,-14,-15,-9,-10,-11,-12,-17,-16,]),'$end':([1,2,3,5,15,17,18,19,20,28,29,30,31,35,36,],[0,-1,-3,-2,-4,-8,-13,-14,-15,-9,-10,-11,-12,-17,-16,]),'ID':([4,7,12,16,21,22,23,24,25,26,37,],[6,8,14,20,20,20,20,20,20,20,20,]),'LPAREN':([6,16,20,21,22,23,24,25,26,37,],[7,21,26,21,21,21,21,21,21,21,]),'RPAREN':([7,8,9,10,14,18,19,20,26,27,28,29,30,31,32,33,34,35,36,38,],[-21,-6,11,-7,-5,-13,-14,-15,-21,35,-9,-10,-11,-12,36,-19,-20,-17,-16,-18,]),'COMMA':([7,8,9,10,14,18,19,20,26,28,29,30,31,32,33,34,35,36,38,],[-21,-6,12,-7,-5,-13,-14,-15,-21,-9,-10,-11,-12,37,-19,-20,-17,-16,-18,]),'COLON':([11,],[13,]),'REMATE':([13,],[16,]),'NUMBER':([16,21,22,23,24,25,26,37,],[19,19,19,19,19,19,19,19,]),'PLUS':([17,18,19,20,27,28,29,30,31,33,35,36,38,],[22,-13,-14,-15,22,-9,-10,-11,-12,22,-17,-16,22,]),'MINUS':([17,18,19,20,27,28,29,30,31,33,35,36,38,],[23,-13,-14,-15,23,-9,-10,-11,-12,23,-17,-16,23,]),'TIMES':([17,18,19,20,27,28,29,30,31,33,35,36,38,],[24,-13,-14,-15,24,24,24,-11,-12,24,-17,-16,24,]),'DIVIDE':([17,18,19,20,27,28,29,30,31,33,35,36,38,],[25,-13,-14,-15,25,25,25,-11,-12,25,-17,-16,25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'function_list':([0,],[2,]),'function':([0,2,],[3,5,]),'param_list':([7,],[9,]),'empty':([7,26,],[10,34,]),'statement':([13,],[15,]),'expression':([16,21,22,23,24,25,26,37,],[17,27,28,29,30,31,33,38,]),'primary':([16,21,22,23,24,25,26,37,],[18,18,18,18,18,18,18,18,]),'arg_list':([26,],[32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> function_list','program',1,'p_program','futbolang_interpreter.py',94),
  ('function_list -> function_list function','function_list',2,'p_function_list','futbolang_interpreter.py',98),
  ('function_list -> function','function_list',1,'p_function_list','futbolang_interpreter.py',99),
  ('function -> JUGADOR ID LPAREN param_list RPAREN COLON statement','function',7,'p_function','futbolang_interpreter.py',106),
  ('param_list -> param_list COMMA ID','param_list',3,'p_param_list','futbolang_interpreter.py',113),
  ('param_list -> ID','param_list',1,'p_param_list','futbolang_interpreter.py',114),
  ('param_list -> empty','param_list',1,'p_param_list','futbolang_interpreter.py',115),
  ('statement -> REMATE expression','statement',2,'p_statement','futbolang_interpreter.py',125),
  ('expression -> expression PLUS expression','expression',3,'p_expression','futbolang_interpreter.py',132),
  ('expression -> expression MINUS expression','expression',3,'p_expression','futbolang_interpreter.py',133),
  ('expression -> expression TIMES expression','expression',3,'p_expression','futbolang_interpreter.py',134),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','futbolang_interpreter.py',135),
  ('expression -> primary','expression',1,'p_expression','futbolang_interpreter.py',136),
  ('primary -> NUMBER','primary',1,'p_primary_number','futbolang_interpreter.py',146),
  ('primary -> ID','primary',1,'p_primary_id','futbolang_interpreter.py',150),
  ('primary -> ID LPAREN arg_list RPAREN','primary',4,'p_primary_fun_call','futbolang_interpreter.py',154),
  ('primary -> LPAREN expression RPAREN','primary',3,'p_primary_paren','futbolang_interpreter.py',158),
  ('arg_list -> arg_list COMMA expression','arg_list',3,'p_arg_list','futbolang_interpreter.py',162),
  ('arg_list -> expression','arg_list',1,'p_arg_list','futbolang_interpreter.py',163),
  ('arg_list -> empty','arg_list',1,'p_arg_list','futbolang_interpreter.py',164),
  ('empty -> <empty>','empty',0,'p_empty','futbolang_interpreter.py',174),
]
